name=Carbonara_DRV8874
version=v0.1.0
author=Carbonara Individuals
maintainer=Daniel Principe (turtlerock0010@gmail.com)
sentence=Arduino library for controlling the DRV8874 motor driver.
paragraph=Carbonara Individuals' Arduino motor driver library for the DRV8874 for easy motor control.
category=Device Control
url=https://github.com/Carbonara-Individuals/Carbonara_DRV8874
architectures=*
license=MIT
